name: bawasa_admin_api
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bcrypt: ^1.1.3
  dart_frog: ^1.1.0
  dart_jsonwebtoken: ^3.2.0
  dotenv: ^4.2.0
  mysql_client: ^0.0.27
  postgres: ^3.5.6

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
